#!/bin/bash

awk 'a==1 {print} /\[DATA\]/ {a=1}' $1 |
sed -r 's/([0-9]{2}:[0-9]{2}:[0-9]{2}):([0-9]{3})(.*)/\1,\2\3/' |
sed 's/\.//' |
sed 's/\t\t/\ts\t/g'|
sed 's/\t\t/\ts\t/g'|
sed 's/\t\n/\ts\n/g'|
sed 's/,/\./g'
