#!/bin/bash

gnuplot -p << GPEND

set terminal x11 size 1400,700
#set output 'test.svg'

set xdata time
set timefmt '%H:%M:%S'

set multiplot layout 2,1

plot "<sudef $1" using 1:3 with lines
plot "<sudef $1" using 1:4 with lines

unset multiplot

GPEND
