#!/bin/bash

gnuplot -p << GPEND

set terminal qt size 1200,600
set nokey
set autoscale xfix
#set grid lt 0 linecolor rgb "gray"

set xdata time
set timefmt '%H:%M:%S'

set multiplot layout 2,1

set ylabel "Pression (cmH₂O)"
plot "<sudef $1" using 1:3 with lines
set ylabel "Débit (l/s)"
plot "<sudef $1" using 1:4 with lines

unset multiplot

GPEND
